Website/auth.py
from flask import Blueprint, flash, render_template, request, url_for, redirect
import os
from werkzeug.utils import redirect, secure_filename
from werkzeug.security import generate_password_hash, check_password_hash
from .forms import LoginForm, RegisterForm
from flask_login import login_user, login_required, logout_user
from . import db
from .models import User

from .event import check_upload_file
# JRD COMMENT


# create a blueprint
bp = Blueprint('auth', __name__)


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = None
    if form.validate_on_submit():
        # get the info input into the form
        inputname = form.user_name.data
        inputpass = form.password.data

        u1 = User.query.filter_by(name=inputname).first()
        if u1 is None:
            error = "Incorrect user name"
            flash(error)
            return redirect(url_for('auth.login'))
        elif not check_password_hash(u1.password_hash, inputpass):
            error = "Incorrect password"
            flash(error)
            return redirect(url_for('auth.login'))
        if error is None:
            login_user(u1)
            print(
                f'Successfully logged in\nUser: {u1.name} \nID: {u1.id}')
            flash('You logged in successfully')
            return redirect(url_for('auth.login'))
    return render_template('forms.html', form=form, heading="Login")


@bp.route('/logout')
def logout():
    logout_user()
    flash('You have logged out')
    return redirect(url_for('auth.login'))


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    db_file_path = check_upload_file(form)
    if (db_file_path == None):
        db_file_path = r"static/images/event_imgs/profile.png"
    #validate_phone('RegisterForm','contact_no')
    if form.validate_on_submit():
        print('Register form submitted')
        uname = form.user_name.data
        pwd = form.password.data
        email = form.email_id.data
        contact = form.contact_no.data
        address = form.address.data
        # generate a hashed pwd for security
        pwd_hash = generate_password_hash(pwd)
        # Create a new user object
        new_user = User(name=uname,
                        emailid=email,
                        password_hash=pwd_hash, image=db_file_path,
                        contact_no=contact,address = address)

        # check if user exist in the database
        exists = db.session.query(User.name).filter_by(
            name=new_user.name).first() is not None

        if not exists:
            db.session.add(new_user)
            db.session.commit()
            flash('Account created sucessfully.')
        else:
            error = 'Account already exists, Please try again'
            flash(error)
            return redirect(url_for('auth.register'))

        return redirect(url_for('auth.login'))

    return render_template('forms.html', form=form, heading="Register Form")

Website/views.py
from re import U
from flask import Blueprint, render_template, url_for, flash, request, redirect, url_for
from . import db
import os
from werkzeug.utils import redirect, secure_filename
from .forms import CreateEvent
from .models import Event, User
from flask_login import login_required, current_user
from .models import Event
from sqlalchemy import func
import math

bp = Blueprint('main', __name__)

choices = ["Mixed Genre", "Pop", "Rock",
           "Country", "Blues", "Techno", "Hip hop"]


@bp.route('/')
def index():
    events = Event.query.all()
    return render_template('index.html', events=events, choices=choices)

# User account details page route


@bp.route('/<id>/details')
@login_required
def details(id):
    user = User.query.filter_by(id=current_user.id).first()
    return render_template('details.html', user=user)

# Search functionality found on index page route


@bp.route('/search')
def search():
    if request.args["search"]:
        print(request.args['search'])
        event_search = "%" + request.args['search'] + '%'
        events = Event.query.filter(Event.title.like(event_search)).all()
        events += Event.query.filter(
            Event.description.like(event_search)).all()
        return render_template('index.html', events=events)
    else:
        return redirect(url_for('main.index'))

# Route used for index page sort by category (in this case musical genre)


@bp.route('/genre')
def genre():
    if request.args["genredrop"] != 'all':
        print(request.args['genredrop'])
        event_search = request.args['genredrop']
        events = Event.query.filter(Event.type.like(event_search)).all()
        return render_template('index.html', events=events)
    else:
        return redirect(url_for('main.index'))

Website/templates/base.html
<!doctype html>
<html lang="en">

<head>

  <script src="https://kit.fontawesome.com/8038ea2620.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" type="text/css" href="../../static/custom.css">


  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

  <title>Eventsy Music</title>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
    crossorigin="anonymous"></script>

</head>



<header>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('main.index')}}">
        <img class="logo" src="../../static/images/logo4.jpg">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{{url_for('main.index')}}">Home</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Events
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                {% if not current_user.is_authenticated %}
                <a class="dropdown-item" href="{{url_for('auth.login')}}">Create Event</a>
                {% else %}
                <a class="dropdown-item" href="{{url_for('event.create')}}">Create Event</a>
                {% endif %}
              </li>
              <li><a class="dropdown-item" href="{{url_for('event.myevents')}}">My Events</a></li>
              <li><a class="dropdown-item" href="{{url_for('event.bookings')}}">Booked Events</a></li>
            </ul>
          </li>
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
              aria-expanded="false">
              Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{url_for('main.details', id=current_user.id)}}">Account Details</a>
              </li>
              <li>
                {% if current_user.is_authenticated %}
                <a class="dropdown-item" href={{url_for('auth.logout')}}>Log out</a>
                {% else %}
                <a class="dropdown-item" href={{url_for('auth.login')}}>Login</a>
                {% endif %}
              </li>
            </ul>
          </li>
          {% endif %}
        </ul>

        {% if current_user.is_authenticated %}
        <div class="d-grid gap-3 d-lg-flex justify-content-md-end">
          <button class="btn btn-success me-md-2" onclick="window.location.href='/logout'" type="button">Logout</button>
        </div>
        {% else %}
        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
          <button class="btn btn-success me-md-2" onclick="window.location.href='/login'" type="button">Sign In |
            Register</button>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>

</header>




<main>

  <body>

    {% block content %}


    {% endblock %}

    <!-- Bootstrap js -->

  </body>

</main>


<footer>

  <div class="d-flex flex-column text-center pt-6">
    <div class="col footicons align-content-center mt-3">
      <a class="me-2" href="https://www.facebook.com/" target="_blank"><i class="fab fa-facebook-square"></i></a>
      <a class="me-2" href="https://twitter.com/joerogan" target="_blank"><i class="fab fa-twitter-square"></i></a>
      <a class="me-2" href="https://www.linkedin.com/feed/" target="_blank"><i class="fab fa-linkedin"></i></a>
      <a class="me-2" href="https://www.instagram.com" target="_blank"><i class="fab fa-instagram-square"></i></a>
      <a class="me-2" href="https://www.youtube.com" target="_blank"><i class="fab fa-youtube-square"></i></a>
    </div>

    <div class="col">
      <p class="text-success mb-0">Copyright © 2021 Eventsy</p>
      <p><a href="#" style="color: green;">Back to top</a></p>
    </div>
  </div>
</footer>


</html>

Website/templates/details.html
{% extends "base.html" %}

{% block content %}

<!-- This page will contain information relating to events that the user has booked -->

<div class="container details_container pt-3">
    <div id="content-wrap">
        <div class="row">
            <h2 class="display-4">Account Information</h2>
            <hr class="solid">
        </div>

        <br>
        <div class="row">
            <div class="col 10">

            <h1 class="display-6">User Name: <u>{{current_user.name}}</u>
            </h1>

            <h1 class="display-6">Email Address: <u>{{current_user.emailid}}</u>
            </h1>

            <h1 class="display-6">Contact Number: <u>{{current_user.contact_no}}</u>
            </h1>
        </div>

        </div>


    </div>

</div>







{% endblock %}

Website/templates/index.html
{% extends "base.html" %}

{% block content %}

<!-- Carousel -->
<div id="carouselExampleIndicators" class="carousel slide carousel-fade text-center" data-bs-ride="carousel"
  data-bs-interval="4000">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
      aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
      aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
      aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">


      <div class="bg-overlay bg_img_1">
        <div class="carousel-container">
          <h1>Welcome to Eventsy</h1>
          {% if current_user.is_authenticated %}
          <h1>{{current_user.name + '!'}}</h1>
          <p class="lead">At Eventsy you can browse, book and track music events that interest you.</p>
          {% else %}
          <p class="lead">At Eventsy you can browse, book and track music events that interest you.</p>
          <a href="{{ url_for('auth.register') }}">
            <button type="button" class="btn btn-lg btn-outline-success mb-2">Sign up now</button>
          </a>
          {% endif %}

        </div>
      </div>
    </div>

    <div class="carousel-item">
      <div class="bg-overlay bg_img_2">
        <div class="carousel-container">
          <h1>Explore Upcoming Artist</h1>
          <p class="lead"> Browse events by genre, artist or location.</p>
          <a href="#events">
            <button type="button" class="btn btn-lg btn-outline-success mb-2">Browse all Events</button>
          </a>
        </div>
      </div>
    </div>


    <div class="carousel-item">

      <div class="bg-overlay bg_img_3">
        <div class="carousel-container">

          <h1>Want to Organise an Event?</h1>
          <p class="lead">Interested in advertising an event? Click below to create an event with Eventsy.
          </p>
          <a href="{{url_for('event.create')}}">
            <button type="button" class="btn btn-lg btn-outline-success mb-2">Be an Organiser</button>
          </a>
        </div>
      </div>
    </div>

  </div>

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
<!-- End carousel -->

<!-- Jumbotron -->
<div class="container text-center">
  <div class="row d-flex py-1 mb-1">
    <div class="jumbo-head container">
      <h1 class="jumbotron-heading">Eventsy</h1>
      <h3>
        <p class="lead text-muted">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Autem in nostrum magnam
          architecto asperiores fugit et facere id, atque quos, molestiae accusantium hic deleniti. Deleniti</p>
        <hr class="index-line">
    </div>
  </div>
  <!--  end Jumbotron -->


  <!-- Search event bar -->
  <div class="row mb-3 d-flex justify-content-center">
    <label for="SearchForm">Search for events:</label>
    <div class="col col-sm-10 col-md-8 col-lg-6">
      <form class="d-flex align-items-center" action="{{url_for('main.search')}}">
        <input type="text" placeholder="Search" name="search" class="form-control flex-grow-1 my-1 mx-1"
          id="SearchForm">
        <button class="btn btn-success btn-outline-sucess" type="submit">Go</button>

      </form>
    </div>
  </div>

  <!-- Option to browse events via category -->
  <div class="row mb-3 d-flex justify-content-center">
    <label for="genre">Filter Events by Musical Genre:</label>
    <div class="col col-sm-10 col-md-8 col-lg-6">
      <form class="d-flex align-items-center" action="{{url_for('main.genre')}}">
        <select class="form-select form-control flex-grow-1 my-1 mx-1" aria-label="Default select example"
          name="genredrop" id="genre">
          <option value="all" selected>All Genres</option>
          <option value="Mixed Genre">Mixed Genres</option>
          <option value="Pop">Pop</option>
          <option value="Rock">Rock</option>
          <option value="Country">Country</option>
          <option value="Blues">Blues</option>
          <option value="Techno">Techno</option>
          <option value="Hip hop">Hip hop</option>
        </select>
        <button class="btn btn-success btn-outline-sucess" type="submit">Go</button>
      </form>
      </ul>
    </div>
  </div>
</div>
<!-- End of funtionality row-->


<!-- Events -->
<div class="container-fluid" id="events">
  <div class="row d-flex align-items-start">
    {% for event in events %}
    <div class="col-xxl-3 col-lg-4 col-md-6 col-sm-7 d-block mx-auto">

      <!-- Card -->
      <div class="card shadow-lg px-3 pb-3 mb-5 bg-body rounded">
        <div class="card-body">


          <!-- Event Status -->

          {% if event.status == "Upcoming" %}

          <span class="position-absolute top-0 start-10 translate-middle badge rounded-pill bg-success">

            {% elif event.status == "Booked Out" %}
            <span class="position-absolute top-0 start-10 translate-middle badge rounded-pill bg-info">

              {% elif event.status == "Cancelled" %}
              <span class="position-absolute top-0 start-10 translate-middle badge rounded-pill bg-danger">

                {% elif event.status == "Inactive" %}

                <span class="position-absolute top-0 start-10 translate-middle badge rounded-pill bg-warning">

                  {% endif %}

                  {{event.status}}
                  <span class="visually-hidden">Event Status</span>
                </span>

                <h4 class="text-center">{{event.title}}</h4>

                <!-- Poster -->

                <div class="d-flex justify-content-center">
                  <img class="card-image d-block mb-2" src="{{event.image}}" alt="Poster of Event No. {{event.id}}">
                </div>


                <!-- Details -->
                <div class="accordion" id="accordionExample">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed btn-outline-success" type="button"
                        data-bs-toggle="collapse" data-bs-target="#eventid{{event.id}}" aria-expanded="true"
                        aria-controls="eventid{{event.id}}">
                        Info
                      </button>
                    </h2>
                    <div id="eventid{{event.id}}" class="accordion-collapse collapse" aria-labelledby="headingOne"
                      data-bs-parent="#accordionExample">
                      <div class="accordion-body">
                        <p>
                          <strong>Artist: </strong>{{event.artist}}<br>
                          <strong>Genre: </strong>{{event.type}}<br>
                          <strong>Venue: </strong>{{event.address}}, {{event.city}}, {{event.suburb}}<br>
                          <strong>Date: </strong>{{event.startdate}}<br>
                          <a href="{{ url_for('event.show', id=event.id) }}"
                            class="btn btn-outline-success d-flex align-items-center">View Details
                          </a>
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</div>


{% endblock %}